In [ ]:
# tensor的创建
import torch

In [2]:
a = torch.tensor([1,2,3], dtype=torch.int32)

In [3]:
print(a)

tensor([1, 2, 3], dtype=torch.int32)


In [4]:
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

In [5]:
# tensor的维度
tensor.ndim

2

In [6]:
# tensor的形状
tensor.shape

torch.Size([3, 3])

In [7]:
# tensor的数据类型
tensor.dtype

torch.int64

In [8]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
torch.zeros(3, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [10]:
# 0-1均匀分布
torch.rand(3, 4)

tensor([[0.3697, 0.0617, 0.5436, 0.7950],
        [0.3574, 0.1615, 0.2976, 0.7273],
        [0.2135, 0.2521, 0.1260, 0.9327]])

In [11]:
# 范围0-10
torch.randint(0, 10, (3, 4))

tensor([[2, 9, 4, 9],
        [2, 1, 6, 6],
        [9, 4, 3, 2]])

In [12]:
# 正态分布
torch.randn(3, 4)

tensor([[-0.2157,  0.9876,  1.0041, -0.5523],
        [ 0.8303,  0.5643, -0.5158, -0.4044],
        [ 0.2313, -0.7277,  1.1607, -0.4695]])

In [13]:
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
a

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [14]:
b = torch.rand_like(a, dtype=torch.float64)
b

tensor([[0.6980, 0.0233, 0.5055],
        [0.0717, 0.4989, 0.4879],
        [0.9463, 0.0334, 0.1750]], dtype=torch.float64)

In [15]:
print(b.shape)
print(b.size())

torch.Size([3, 3])
torch.Size([3, 3])


In [16]:
b.view(9)

tensor([0.6980, 0.0233, 0.5055, 0.0717, 0.4989, 0.4879, 0.9463, 0.0334, 0.1750],
       dtype=torch.float64)

In [17]:
b.view(3, 3)

tensor([[0.6980, 0.0233, 0.5055],
        [0.0717, 0.4989, 0.4879],
        [0.9463, 0.0334, 0.1750]], dtype=torch.float64)

In [18]:
print(b[1])

tensor([0.0717, 0.4989, 0.4879], dtype=torch.float64)


In [19]:
# tensor和numpy的相互转换
import numpy as np

In [20]:
np.array(b)

array([[0.69803769, 0.02330337, 0.50549543],
       [0.0717101 , 0.49887644, 0.48792692],
       [0.94631378, 0.03340956, 0.17498314]])

In [21]:
array = np.array([1, 2, 3])
array

array([1, 2, 3])

In [22]:
tensor = torch.tensor(array)
tensor

tensor([1, 2, 3], dtype=torch.int32)

In [23]:
array = np.array(tensor)
array

array([1, 2, 3])

In [24]:
# tensor的运算
a = torch.randint(1, 5, (2, 3))
b = torch.randint(1, 5, (2, 3))
print(a)
print(b)

tensor([[1, 4, 1],
        [2, 2, 2]])
tensor([[3, 3, 3],
        [2, 1, 2]])


In [25]:
# 加法
a + b

tensor([[4, 7, 4],
        [4, 3, 4]])

In [26]:
torch.add(a, b)

tensor([[4, 7, 4],
        [4, 3, 4]])

In [27]:
# 减法
a - b

tensor([[-2,  1, -2],
        [ 0,  1,  0]])

In [28]:
torch.sub(a, b)

tensor([[-2,  1, -2],
        [ 0,  1,  0]])

In [29]:
# 乘法
a * b

tensor([[ 3, 12,  3],
        [ 4,  2,  4]])

In [30]:
torch.mul(a, b)

tensor([[ 3, 12,  3],
        [ 4,  2,  4]])

In [31]:
# 除法
a / b

tensor([[0.3333, 1.3333, 0.3333],
        [1.0000, 2.0000, 1.0000]])

In [32]:
torch.div(a, b)

tensor([[0.3333, 1.3333, 0.3333],
        [1.0000, 2.0000, 1.0000]])

In [33]:
# 取余数
a % b

tensor([[1, 1, 1],
        [0, 0, 0]])

In [34]:
torch.remainder(a, b)

tensor([[1, 1, 1],
        [0, 0, 0]])

In [35]:
# 整除
a // b

tensor([[0, 1, 0],
        [1, 2, 1]])

In [36]:
torch.floor_divide(a, b)

tensor([[0, 1, 0],
        [1, 2, 1]])

In [37]:
# 指数
a ** b

tensor([[ 1, 64,  1],
        [ 4,  2,  4]])

In [38]:
torch.pow(a, b)

tensor([[ 1, 64,  1],
        [ 4,  2,  4]])

In [39]:
# 矩阵乘法
tensor = torch.ones(3, 5)
tensor

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [40]:
tensor2 = torch.rand(5, 4)

In [41]:
# 3*5 5*4 = 3*4
torch.matmul(tensor, tensor2)

tensor([[1.5500, 1.4884, 2.3842, 3.0816],
        [1.5500, 1.4884, 2.3842, 3.0816],
        [1.5500, 1.4884, 2.3842, 3.0816]])

In [42]:
# 矩阵转置 3*5 -> 5*3
tensor.T

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [43]:
sample = torch.rand(3, 4)
sample

tensor([[0.6646, 0.9070, 0.1114, 0.1310],
        [0.8109, 0.2013, 0.1891, 0.5051],
        [0.6896, 0.1152, 0.8575, 0.2260]])

In [44]:
# 求和
torch.sum(sample)

tensor(5.4086)

In [45]:
# 按行求和
torch.sum(sample, dim=1)

tensor([1.8140, 1.7064, 1.8882])

In [46]:
torch.min(sample)

tensor(0.1114)

In [47]:
torch.max(sample)

tensor(0.9070)

In [48]:
# 求最小值的索引
torch.argmin(sample)

tensor(2)

In [49]:
# 求最大值的索引
torch.argmax(sample)

tensor(1)

In [50]:
# 求均值
torch.mean(sample)

tensor(0.4507)

In [51]:
# 求中位数
torch.median(sample)

tensor(0.2260)

In [52]:
# 求标准差
torch.std(sample)

tensor(0.3191)

In [53]:
# 求方差
torch.var(sample)

tensor(0.1018)

In [54]:
## tensor的索引和切片
tensor = torch.arange(2, 14)
tensor

tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [55]:
print(tensor[2])

tensor(4)


In [56]:
print(tensor[2:5])

tensor([4, 5, 6])


In [57]:
print(tensor[2:])

tensor([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])


In [58]:
print(tensor[:5])

tensor([2, 3, 4, 5, 6])


In [59]:
# 从索引2开始，每隔2个取一个
print(tensor[2:10:2])

tensor([ 4,  6,  8, 10])


In [60]:
print(tensor[2:-1])

tensor([ 4,  5,  6,  7,  8,  9, 10, 11, 12])


In [61]:
index = [2, 3, 5, 7]
tensor[index]

tensor([4, 5, 7, 9])