In [1]:
import torch

# tensor的创建

In [2]:
a = torch.tensor([1,2,3], dtype=torch.int32)

In [3]:
print(a)

tensor([1, 2, 3], dtype=torch.int32)


In [4]:
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

In [5]:
# tensor的维度
tensor.ndim

2

In [6]:
# tensor的形状
tensor.shape

torch.Size([3, 3])

In [7]:
# tensor的数据类型
tensor.dtype

torch.int64

In [8]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
torch.zeros(3, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [10]:
# 0-1均匀分布
torch.rand(3, 4)

tensor([[0.1564, 0.5027, 0.5520, 0.1861],
        [0.9238, 0.2819, 0.9908, 0.8555],
        [0.2229, 0.9681, 0.1154, 0.7763]])

In [13]:
# 范围0-10
torch.randint(0, 10, (3, 4))

tensor([[2, 3, 4, 7],
        [2, 6, 0, 4],
        [5, 4, 4, 2]])

In [12]:
# 正态分布
torch.randn(3, 4)

tensor([[-0.5531,  0.6215,  1.1219, -0.4353],
        [-1.0802,  0.0648, -0.8041, -1.1565],
        [-0.2825,  0.6631, -0.7387,  0.3390]])

In [15]:
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
a

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [16]:
b = torch.rand_like(a, dtype=torch.float64)
b

tensor([[0.7613, 0.8169, 0.4172],
        [0.8705, 0.4038, 0.8633],
        [0.9633, 0.8144, 0.0474]], dtype=torch.float64)

In [17]:
print(b.shape)
print(b.size())

torch.Size([3, 3])
torch.Size([3, 3])


In [18]:
b.view(9)

tensor([0.7613, 0.8169, 0.4172, 0.8705, 0.4038, 0.8633, 0.9633, 0.8144, 0.0474],
       dtype=torch.float64)

In [19]:
b.view(3, 3)

tensor([[0.7613, 0.8169, 0.4172],
        [0.8705, 0.4038, 0.8633],
        [0.9633, 0.8144, 0.0474]], dtype=torch.float64)

In [22]:
print(b[1])

tensor([0.8705, 0.4038, 0.8633], dtype=torch.float64)


# tensor和numpy的相互转换

In [23]:
import numpy as np

In [27]:
np.array(b)

array([[0.76131491, 0.81693632, 0.41716091],
       [0.87049372, 0.40375262, 0.86329388],
       [0.96328689, 0.81436123, 0.04738632]])

In [29]:
array = np.array([1, 2, 3])
array

array([1, 2, 3])

In [30]:
tensor = torch.tensor(array)
tensor

tensor([1, 2, 3], dtype=torch.int32)

In [32]:
array = np.array(tensor)
array

array([1, 2, 3])

# tensor的运算

In [33]:
a = torch.randint(1, 5, (2, 3))
b = torch.randint(1, 5, (2, 3))
print(a)
print(b)

tensor([[2, 1, 2],
        [3, 3, 3]])
tensor([[4, 1, 3],
        [2, 1, 4]])


## 加法

In [34]:
a + b

tensor([[6, 2, 5],
        [5, 4, 7]])

In [35]:
torch.add(a, b)

tensor([[6, 2, 5],
        [5, 4, 7]])

## 减法

In [40]:
a - b

tensor([[-2,  0, -1],
        [ 1,  2, -1]])

In [41]:
torch.sub(a, b)

tensor([[-2,  0, -1],
        [ 1,  2, -1]])

## 乘法

In [42]:
a * b

tensor([[ 8,  1,  6],
        [ 6,  3, 12]])

In [43]:
torch.mul(a, b)

tensor([[ 8,  1,  6],
        [ 6,  3, 12]])

## 除法

In [44]:
a / b

tensor([[0.5000, 1.0000, 0.6667],
        [1.5000, 3.0000, 0.7500]])

In [45]:
torch.div(a, b)

tensor([[0.5000, 1.0000, 0.6667],
        [1.5000, 3.0000, 0.7500]])

## 取余数

In [46]:
a % b

tensor([[2, 0, 2],
        [1, 0, 3]])

In [47]:
torch.remainder(a, b)

tensor([[2, 0, 2],
        [1, 0, 3]])

## 整除

In [48]:
a // b

tensor([[0, 1, 0],
        [1, 3, 0]])

In [49]:
torch.floor_divide(a, b)

tensor([[0, 1, 0],
        [1, 3, 0]])

## 指数

In [50]:
a ** b

tensor([[16,  1,  8],
        [ 9,  3, 81]])

In [51]:
torch.pow(a, b)

tensor([[16,  1,  8],
        [ 9,  3, 81]])

## 矩阵乘法

In [52]:
tensor = torch.ones(3, 5)
tensor

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [53]:
tensor2 = torch.rand(5, 4)

In [56]:
# 3*5 5*4 = 3*4
torch.matmul(tensor, tensor2)

tensor([[3.2678, 3.2557, 1.0694, 2.7519],
        [3.2678, 3.2557, 1.0694, 2.7519],
        [3.2678, 3.2557, 1.0694, 2.7519]])

In [57]:
# 矩阵转置 3*5 -> 5*3
tensor.T

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [58]:
sample = torch.rand(3, 4)
sample

tensor([[0.3071, 0.4825, 0.7974, 0.0313],
        [0.6298, 0.4124, 0.5108, 0.3009],
        [0.9927, 0.5688, 0.8768, 0.1493]])

In [59]:
# 求和
torch.sum(sample)

tensor(6.0598)

In [62]:
# 按行求和
torch.sum(sample, dim=1)

tensor([1.6184, 1.8538, 2.5876])

In [63]:
torch.min(sample)

tensor(0.0313)

In [65]:
torch.max(sample)

tensor(0.9927)

In [67]:
# 求最小值的索引
torch.argmin(sample)

tensor(3)

In [68]:
# 求最大值的索引
torch.argmax(sample)

tensor(8)

In [69]:
# 求均值
torch.mean(sample)

tensor(0.5050)

In [70]:
# 求中位数
torch.median(sample)

tensor(0.4825)

In [72]:
# 求标准差
torch.std(sample)

tensor(0.2895)

In [75]:
# 求方差
torch.var(sample)

tensor(0.0838)

## tensor的索引和切片

In [91]:
tensor = torch.arange(2, 14)
tensor

tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [83]:
print(tensor[2])

tensor(4)


In [84]:
print(tensor[2:5])

tensor([4, 5, 6])


In [85]:
print(tensor[2:])

tensor([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])


In [86]:
print(tensor[:5])

tensor([2, 3, 4, 5, 6])


In [87]:
# 从索引2开始，每隔2个取一个
print(tensor[2:10:2])

tensor([ 4,  6,  8, 10])


In [88]:
print(tensor[2:-1])

tensor([ 4,  5,  6,  7,  8,  9, 10, 11, 12])


In [92]:
index = [2, 3, 5, 7]
tensor[index]

tensor([4, 5, 7, 9])