In [1]:
import torch

# tensor的创建

In [2]:
a = torch.tensor([1,2,3], dtype=torch.int32)

In [3]:
print(a)

tensor([1, 2, 3], dtype=torch.int32)


In [4]:
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

In [5]:
# tensor的维度
tensor.ndim

2

In [6]:
# tensor的形状
tensor.shape

torch.Size([3, 3])

In [7]:
# tensor的数据类型
tensor.dtype

torch.int64

In [8]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
torch.zeros(3, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [10]:
# 0-1均匀分布
torch.rand(3, 4)

tensor([[0.9108, 0.9088, 0.6349, 0.0665],
        [0.1569, 0.0235, 0.1093, 0.0719],
        [0.1127, 0.1265, 0.6014, 0.3072]])

In [11]:
# 范围0-10
torch.randint(0, 10, (3, 4))

tensor([[5, 8, 2, 8],
        [9, 0, 3, 0],
        [6, 2, 5, 3]])

In [12]:
# 正态分布
torch.randn(3, 4)

tensor([[-0.7482, -0.3985,  0.6787,  0.4179],
        [-0.3916, -0.4392, -0.6618, -1.2359],
        [ 0.3054, -0.9504, -1.4038,  0.6100]])

In [13]:
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
a

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [14]:
b = torch.rand_like(a, dtype=torch.float64)
b

tensor([[0.8675, 0.5694, 0.4616],
        [0.9593, 0.9309, 0.6404],
        [0.6548, 0.9416, 0.5555]], dtype=torch.float64)

In [15]:
print(b.shape)
print(b.size())

torch.Size([3, 3])
torch.Size([3, 3])


In [16]:
b.view(9)

tensor([0.8675, 0.5694, 0.4616, 0.9593, 0.9309, 0.6404, 0.6548, 0.9416, 0.5555],
       dtype=torch.float64)

In [17]:
b.view(3, 3)

tensor([[0.8675, 0.5694, 0.4616],
        [0.9593, 0.9309, 0.6404],
        [0.6548, 0.9416, 0.5555]], dtype=torch.float64)

In [18]:
print(b[1])

tensor([0.9593, 0.9309, 0.6404], dtype=torch.float64)


# tensor和numpy的相互转换

In [19]:
import numpy as np

In [20]:
np.array(b)

array([[0.86750878, 0.56937536, 0.46157815],
       [0.95933   , 0.93089316, 0.6404183 ],
       [0.65483081, 0.94159645, 0.55545431]])

In [21]:
array = np.array([1, 2, 3])
array

array([1, 2, 3])

In [22]:
tensor = torch.tensor(array)
tensor

tensor([1, 2, 3], dtype=torch.int32)

In [23]:
array = np.array(tensor)
array

array([1, 2, 3])

# tensor的运算

In [24]:
a = torch.randint(1, 5, (2, 3))
b = torch.randint(1, 5, (2, 3))
print(a)
print(b)

tensor([[1, 3, 3],
        [3, 3, 4]])
tensor([[2, 2, 2],
        [3, 3, 2]])


## 加法

In [25]:
a + b

tensor([[3, 5, 5],
        [6, 6, 6]])

In [26]:
torch.add(a, b)

tensor([[3, 5, 5],
        [6, 6, 6]])

## 减法

In [27]:
a - b

tensor([[-1,  1,  1],
        [ 0,  0,  2]])

In [28]:
torch.sub(a, b)

tensor([[-1,  1,  1],
        [ 0,  0,  2]])

## 乘法

In [29]:
a * b

tensor([[2, 6, 6],
        [9, 9, 8]])

In [30]:
torch.mul(a, b)

tensor([[2, 6, 6],
        [9, 9, 8]])

## 除法

In [31]:
a / b

tensor([[0.5000, 1.5000, 1.5000],
        [1.0000, 1.0000, 2.0000]])

In [32]:
torch.div(a, b)

tensor([[0.5000, 1.5000, 1.5000],
        [1.0000, 1.0000, 2.0000]])

## 取余数

In [33]:
a % b

tensor([[1, 1, 1],
        [0, 0, 0]])

In [34]:
torch.remainder(a, b)

tensor([[1, 1, 1],
        [0, 0, 0]])

## 整除

In [35]:
a // b

tensor([[0, 1, 1],
        [1, 1, 2]])

In [36]:
torch.floor_divide(a, b)

tensor([[0, 1, 1],
        [1, 1, 2]])

## 指数

In [37]:
a ** b

tensor([[ 1,  9,  9],
        [27, 27, 16]])

In [38]:
torch.pow(a, b)

tensor([[ 1,  9,  9],
        [27, 27, 16]])

## 矩阵乘法

In [39]:
tensor = torch.ones(3, 5)
tensor

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [40]:
tensor2 = torch.rand(5, 4)

In [41]:
# 3*5 5*4 = 3*4
torch.matmul(tensor, tensor2)

tensor([[2.1222, 3.4610, 2.6557, 2.8531],
        [2.1222, 3.4610, 2.6557, 2.8531],
        [2.1222, 3.4610, 2.6557, 2.8531]])

In [42]:
# 矩阵转置 3*5 -> 5*3
tensor.T

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [43]:
sample = torch.rand(3, 4)
sample

tensor([[0.5450, 0.2659, 0.5431, 0.9330],
        [0.9780, 0.0540, 0.4550, 0.8579],
        [0.4729, 0.8918, 0.7748, 0.6325]])

In [44]:
# 求和
torch.sum(sample)

tensor(7.4040)

In [45]:
# 按行求和
torch.sum(sample, dim=1)

tensor([2.2870, 2.3450, 2.7720])

In [46]:
torch.min(sample)

tensor(0.0540)

In [47]:
torch.max(sample)

tensor(0.9780)

In [48]:
# 求最小值的索引
torch.argmin(sample)

tensor(5)

In [49]:
# 求最大值的索引
torch.argmax(sample)

tensor(4)

In [50]:
# 求均值
torch.mean(sample)

tensor(0.6170)

In [51]:
# 求中位数
torch.median(sample)

tensor(0.5450)

In [52]:
# 求标准差
torch.std(sample)

tensor(0.2839)

In [53]:
# 求方差
torch.var(sample)

tensor(0.0806)

## tensor的索引和切片

In [54]:
tensor = torch.arange(2, 14)
tensor

tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [55]:
print(tensor[2])

tensor(4)


In [56]:
print(tensor[2:5])

tensor([4, 5, 6])


In [57]:
print(tensor[2:])

tensor([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])


In [58]:
print(tensor[:5])

tensor([2, 3, 4, 5, 6])


In [59]:
# 从索引2开始，每隔2个取一个
print(tensor[2:10:2])

tensor([ 4,  6,  8, 10])


In [60]:
print(tensor[2:-1])

tensor([ 4,  5,  6,  7,  8,  9, 10, 11, 12])


In [61]:
index = [2, 3, 5, 7]
tensor[index]

tensor([4, 5, 7, 9])